apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderer1
  labels:
    app: fabric
    role: orderer1
spec:
  replicas: 1
  template:
    metadata:
      name: orderer1
      labels:
        role: orderer1
    spec:
      restartPolicy: Always
      containers:
        - name: orderer-container
          # imagePullPolicy: Never
          image: library/orderer1:1.4.1
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
#          volumeMounts:
#            - mountPath: /var/hyperledger/orderer
#              name: orderer-vol
          env:
            - name: ORDERER_GENERAL_LOGLEVEL
              value: "DEBUG"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/var/hyperledger/orderer/genesis.block"
            - name: ORDERER_GENERAL_GENESISPROFILE
              value: initial
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "orderer1"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/var/hyperledger/orderer/msp"
            - name: ORDERER_GENERAL_LEDGERTYPE
              value: "file"
            - name: ORDERER_GENERAL_BATCHTIMEOUT
              value: "2s"
            - name: ORDERER_GENERAL_MAXMESSAGECOUNT
              value: "10"
            - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
              value: "10"
            - name: ORDERER_GENERAL_MAXWINDOWSIZE
              value: "1000"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "false"
            - name: ORDERER_RAMLEDGER_HISTORY_SIZE
              value: "100"
            - name: CONFIGTX_ORDERER_ORDERERTYPE
              value: "etcdraft"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/var/hyperledger/orderer/tls/server.key"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/var/hyperledger/orderer/tls/server.crt"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
          command:
            - orderer
            - start
#            - /bin/bash
#            - -c
#            - 'while true; do sleep 20170504; done'
#      volumes:
#        - name: orderer-vol
#          hostPath:
#            path: /data/driving-files/orderer
---
apiVersion: v1
kind: Service
metadata:
  name: orderer1-service
  labels:
    app: fabric
spec:
  type: ClusterIP
  ports:
    - name: "7050"
      targetPort: 7050
      port: 7050
  selector:
    role: orderer1
