apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        rewrite {
            name regex peer0\.further\.com\.$ peer0-further.default.svc.cluster.local
            answer name peer0-further\.default\.svc\.cluster\.local\.$ peer0.further.com
        }
        rewrite {
            name regex peer0\.blue-agencies\.com\.$ peer0-blue-agencies.default.svc.cluster.local
            answer name peer0-blue-agencies\.default\.svc\.cluster\.local\.$ peer0.blue-agencies.com
        }
        rewrite {
            name regex peer0\.blue-airline\.com\.$ peer0-blue-airline.default.svc.cluster.local
            answer name peer0-blue-airline\.default\.svc\.cluster\.local\.$ peer0.blue-airline.com
        }
        rewrite {
            name regex peer0\.green-agencies\.com\.$ peer0-green-agencies.default.svc.cluster.local
            answer name peer0-green-agencies\.default\.svc\.cluster\.local\.$ peer0.green-agencies.com
        }
        rewrite {
            name regex peer0\.green-airline\.com\.$ peer0-green-airline.default.svc.cluster.local
            answer name peer0-green-airline\.default\.svc\.cluster\.local\.$ peer0.green-airline.com
        }
        rewrite {
            name regex orderer1\.orderer\.$ orderer1-orderer.default.svc.cluster.local
            answer name orderer1-orderer\.default\.svc\.cluster\.local\.$ orderer1
        }
        rewrite {
            name regex orderer2\.orderer\.$ orderer2-orderer.default.svc.cluster.local
            answer name orderer2-orderer\.default\.svc\.cluster\.local\.$ orderer2
        }
        rewrite {
            name regex orderer3\.orderer\.$ orderer3-orderer.default.svc.cluster.local
            answer name orderer3-orderer\.default\.svc\.cluster\.local\.$ orderer3
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system