# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: orderer.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org Green Airline
  # ---------------------------------------------------------------------------
  - Name: GreenAirline
    Domain: greenairline.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Blue Airline:
  # ---------------------------------------------------------------------------
  - Name: BlueAirline
    Domain: blueairline.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Green Agencies:
  # ---------------------------------------------------------------------------
  - Name: GreenAgencies
    Domain: greenagencies.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Blue Agencies:
  # ---------------------------------------------------------------------------
  - Name: BlueAgencies
    Domain: blueagencies.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Billing Settlement Provider
  # ---------------------------------------------------------------------------
  - Name: Bsps
    Domain: bsps.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
      