# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
#  - Name: orderer-one
#    Domain: orderer
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
#    Specs:
#      - Hostname: orderer-one
#  - Name: orderer-two
#    Domain: orderer
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
#    Specs:
#      - Hostname: orderer-two
#  - Name: orderer-three
#    Domain: orderer
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
#    Specs:
#      - Hostname: orderer-three

  - Name: orderer
    Domain: orderer
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3
      
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org Green Airline
  # ---------------------------------------------------------------------------
  - Name: green-airline
    Domain: green-airline
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Blue Airline:
  # ---------------------------------------------------------------------------
  - Name: blue-airline
    Domain: blue-airline
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Green Agencies:
  # ---------------------------------------------------------------------------
  - Name: green-agencies
    Domain: green-agencies
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Blue Agencies:
  # ---------------------------------------------------------------------------
  - Name: blue-agencies
    Domain: blue-agencies
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org Further Networks
  # ---------------------------------------------------------------------------
  - Name: further
    Domain: further
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
      