################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &orderer
        Name: orderer
        ID: orderer
        MSPDir: crypto-config/ordererOrganizations/orderer.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('orderer.member')
            Writers:
                Type: Signature
                Rule: OR('orderer.member')
            Admins:
                Type: Signature
                Rule: OR('orderer.admin')
        
    - &green-airline
        Name: green-airline
        ID: green-airline
        MSPDir: crypto-config/peerOrganizations/green-airline.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('green-airline.admin', 'green-airline.peer', 'green-airline.client')
            Writers:
                Type: Signature
                Rule: OR('green-airline.admin', 'green-airline.client')
            Admins:
                Type: Signature
                Rule: OR('green-airline.admin')
        AnchorPeers:
            - Host: peer0.green-airline.com
              Port: 7051

    - &blue-airline
        Name: blue-airline
        ID: blue-airline
        MSPDir: crypto-config/peerOrganizations/blue-airline.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('blue-airline.admin', 'blue-airline.peer', 'blue-airline.client' )
            Writers:
                Type: Signature
                Rule: OR('blue-airline.admin', 'blue-airline.client')
            Admins:
                Type: Signature
                Rule: OR('blue-airline.admin')
        AnchorPeers:
            - Host: peer0.blue-airline.com
              Port: 7051

    - &green-agencies
        Name: green-agencies
        ID: green-agencies
        MSPDir: crypto-config/peerOrganizations/green-agencies.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('green-agencies.admin', 'green-agencies.peer', 'green-agencies.client')
            Writers:
                Type: Signature
                Rule: OR('green-agencies.admin', 'green-agencies.client')
            Admins:
                Type: Signature
                Rule: OR('green-agencies.admin')
        AnchorPeers:
            - Host: peer0.green-agencies.com
              Port: 7051

    - &blue-agencies
        Name: blue-agencies
        ID: blue-agencies
        MSPDir: crypto-config/peerOrganizations/blue-agencies.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('blue-agencies.admin', 'blue-agencies.peer', 'blue-agencies.client')
            Writers:
                Type: Signature
                Rule: OR('blue-agencies.admin', 'blue-agencies.client')
            Admins:
                Type: Signature
                Rule: OR('blue-agencies.admin')
        AnchorPeers:
            - Host: peer0.blue-agencies.com
              Port: 7051
 
    - &further
        Name: further
        ID: further
        MSPDir: crypto-config/peerOrganizations/further.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: OR('further.admin', 'further.peer', 'further.client')
            Writers:
                Type: Signature
                Rule: OR('further.admin', 'further.client')
            Admins:
                Type: Signature
                Rule: OR('further.admin')
        AnchorPeers:
            - Host: peer0.further.com
              Port: 7051


    
##################################################################################
Channel: &ChannelDefaults
    Capabilities:
        V1_3: true
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: ANY Readers
        Writers:
            Type: ImplicitMeta
            Rule: ANY Writers
        Admins:
            Type: ImplicitMeta
            Rule: MAJORITY Admins


################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo
    Capabilities:
        V1_1: true

    Addresses:
        - orderer:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins
        BlockValidation:
            Type: ImplicitMeta
            Rule: ANY Writers

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
    Capabilities:
        V1_3: true
    Policies:
        Readers:
          Type: ImplicitMeta
          Rule: ANY Readers
        Writers:
          Type: ImplicitMeta
          Rule: ANY Writers
        Admins:
          Type: ImplicitMeta
          Rule: MAJORITY Admins

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
    
##################################################################################
Profiles:

    LocalDev:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *orderer
        Application:
            <<: *ApplicationDefaults
        Consortiums:
            FurtherConsortium:
                Organizations:
                    - *green-airline
                    - *green-agencies
                    - *blue-airline
                    - *blue-agencies
                    - *further

    GreenChannel:
        Consortium: FurtherConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *green-airline
                - *green-agencies
                - *further

    BlueChannel:
        Consortium: FurtherConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *blue-airline
                - *blue-agencies
                - *further
